[package]
name = "lunarity"
version = "0.1.0"
authors = ["Maciej Hirsz <maciej.hirsz@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/maciejhirsz/lunarity"

[dependencies]
toolshed = { version = "0.4" }

[dev-dependencies]
pretty_assertions = "0.4"
