[package]
name = "lunarity-parser"
version = "0.1.0"
authors = ["Maciej Hirsz <maciej.hirsz@gmail.com>"]

[dependencies]
toolshed = "0.4"
lunarity-lexer = { path ="../lexer" }
lunarity-ast = { path = "../ast" }

[dev-dependencies]
pretty_assertions = "0.4"